Add screen lock feature in ExoPlayer
jellyfin/jellyfin-android pull request #108
Opened 2020-09-08 20:55 UTC by CarlosOlivo

Closes #77 

Also enable missing external player feature setting in #98

2020-09-08 20:58 UTC, Maxr1998 commented
About the external player feature, I actually just pushed a PR that moves the external player selection to the native client settings :sweat_smile:
So, you can remove that code again ^^

2020-09-08 21:00 UTC, CarlosOlivo commented
> About the external player feature, I actually just pushed a PR that moves the external player selection to the native client settings 😅
> So, you can remove that code again ^^

Nice timing.

2020-09-08 21:02 UTC, Maxr1998 commented
> Nice timing.

Yeah, sorry. We quickly spotted this after (actually even before) merging the PR yesterday, and decided to merge the player settings to a single location. I started working on it yesterday evening, but only finished it a short while ago.

2020-09-08 21:19 UTC, Maxr1998 requested changes

2020-09-08 21:19 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
> +    width = size.x
```suggestion
    val size = Point().also(display::getSize)
    val height = size.y
    val width = size.x
```

2020-09-08 21:19 UTC, Maxr1998 commented on app/src/main/res/layout/activity_player.xml
> +            android:background="@drawable/ic_screen_unlock_white_24dp"
```suggestion
            android:src="@drawable/ic_screen_unlock_white_24dp"
```

2020-09-08 21:19 UTC, Maxr1998 commented on app/src/main/res/layout/activity_player.xml
> +            android:background="@drawable/ic_screen_unlock_white_24dp"
You might want to add an actual background to ensure the button is always visible above the movie content, maybe a scrim/shadow, or a semi-transparent circle/rounded square.

2020-09-08 21:19 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
> +        }
Could you try to merge this with the `GestureDetector` above?

2020-09-08 21:19 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
> +    private val unlockScreenButton: View = activity.findViewById(R.id.unlock_screen_button)
You can move those above the subtitles button to follow the order of the layout (and while you're at it maybe also swap the audio and subtitles buttons, oops)

2020-09-08 21:20 UTC, Maxr1998 commented
Thanks a lot for the PR, the code looks really good! Have some small issues I spotted, would appreciate if you could resolve them :innocent:

2020-09-08 21:23 UTC, CarlosOlivo commented
> > Nice timing.
> 
> Yeah, sorry 🙈
> We quickly spotted this after (actually even before) merging the PR yesterday, and decided to merge the player settings to a single location. I started working on it yesterday evening, but only finished it a short while ago.

Well, I can say the same, I started working on this since yesterday and just finish it now, sorry for the spam.
Now the PR is as it should be from the beginning. I will check what I can correct.

2020-09-09 03:45 UTC, CarlosOlivo commented
I don't know if it's an error or WIP, but ExoPlayer now don't report when the playback stops or ends, it keeps reporting "/Sessions /Playing/Progress", in the background, I don't know since when, in the v2.0.0-rc.3 version it works correctly, reporting "/Sessions/Playing/Stopped" at the end. @Maxr1998 @nielsvanvelzen

2020-09-09 06:45 UTC, nielsvanvelzen commented
That might be a regression of #104. We'll need to look into that.

2020-09-09 07:54 UTC, Maxr1998 commented
> I don't know if it's an error or WIP, but ExoPlayer now don't report when the playback stops or ends, it keeps reporting "/Sessions /Playing/Progress", in the background, I don't know since when, in the v2.0.0-rc.3 version it works correctly, reporting "/Sessions/Playing/Stopped" at the end. @Maxr1998 @nielsvanvelzen 

Interesting, in my testing it successfully marked the title as played, but that may be because the progress was high enough (you can set in Jellyfin after what percentage played it's considered as watched, after all). I previously thought that the ending submission works by setting the progress to the runtime length, but there seems to be another API route then. I'll investigate.

2020-09-09 10:01 UTC, Maxr1998 approved these changes
I'll give this another test locally, and merge it afterwards :+1:

2020-09-09 10:24 UTC, merged

2020-09-09 10:25 UTC, Maxr1998 commented
Thanks again for the PR @CarlosOlivo, looking forward to see more contributions from you in the future!