Update jellyfin-sdk-kotlin to v1.6.1
jellyfin/jellyfin-android pull request #1506
Opened 2024-11-04 23:56 UTC by jakobkukla

**Changes**

Updated SDK version and fixed build errors.

Also added the API authorization header to exoplayer since the access token is no longer passed via URL for Android Auto (see https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/871).

I have tested the Android Auto functionality and it seems to work fine. The only thing I cannot test and suspect that may not work is casting. Not sure how I would add the header there since CastPlayer cannot use a DataSource.Factory. In https://github.com/google/ExoPlayer/issues/4760 they claim that the receiver app is responsible for authentication. Not sure if this is implemented in [jellyfin/jellyfin-chromecast](https://github.com/jellyfin/jellyfin-chromecast) though.

2024-11-05 11:39 UTC, nielsvanvelzen requested changes

2024-11-05 11:39 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
> +                    "Version=\"${apiClient.clientInfo.version}\""
The SDK has an AuthorizationHeaderBuilder utility for this that has proper escaping

2024-11-05 12:16 UTC, nielsvanvelzen requested changes

2024-11-05 12:16 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
> +        }
Some sources, like Live TV and strm files do not load video through the Jellyfin server but from other origins directly. We should **never** sent the Jellyfin access token to those origins.

2024-11-05 12:16 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
> +            response.items.firstOrNull()
The UserLibraryApi has a getItem operation that would be more efficient

2024-12-17 17:27 UTC, satmandu commented
Any chance of getting this reviewed again @nielsvanvelzen ? It would be nice to start generating builds from the updated sdk...

2024-12-17 18:00 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
> +                dataSpec.withRequestHeaders(hashMapOf("Authorization" to authorizationHeaderString))
This is unsafe as in some cases (like strm files and livestreams) the stream is not loaded from Jellyfin but from an external URL. We should **never** send the Jellyfin authorization header to those sources.

2024-12-17 18:03 UTC, nielsvanvelzen submitted a review, later dismissed
I did not test these changes and only reviewed the usages of the SDK. Those all look fine to me.

2024-12-17 18:10 UTC, satmandu commented
Would someone be so kind as to trigger the build and test workflows on this PR?

2024-12-17 18:22 UTC, nielsvanvelzen commented
GH does not let me trigger the builds so the pull request probably needs to be rebased or have master merged into it.

2024-12-17 23:48 UTC, jakobkukla commented
rebased on master. I think you should be able to trigger the build now @nielsvanvelzen

2025-01-18 17:26 UTC, jakobkukla commented
I think this is ready to merge @nielsvanvelzen :)

2025-01-26 01:43 UTC, Maxr1998 approved these changes

2025-01-26 01:44 UTC, Maxr1998 commented
Thanks for the migration!

2025-01-26 01:44 UTC, merged