Replace GH_TOKEN with ORG_PAT
jellyfin/jellyfin-android pull request #384
Opened 2021-05-12 19:33 UTC by ferferga

``GH_TOKEN`` seems to be used internally by GitHub and it's making some actions we're using in some repos fail ([Source](https://github.com/alex-page/github-project-automation-plus/issues/39))

*(PRs made from users of the org are always successful, but PRs that aren't don't work, like Dependabot PRs. This can be checked by looking at the history of server repos and Jellyfin Vue)*

The org-wide secret should be renamed to something else to avoid confusion and further replacements or messes in GH's side. This PR replaces ``GH_TOKEN`` with ``ORG_PAT``, which should be pretty generic.

2021-05-12 20:49 UTC, nielsvanvelzen commented
While you're at it, can you add the token to gradlew-update.yaml too?

2021-05-13 17:50 UTC, ferferga commented
@nielsvanvelzen Done!

2021-05-13 17:59 UTC, nielsvanvelzen requested changes

2021-05-13 17:59 UTC, nielsvanvelzen commented on .github/workflows/merge-conflict-labeler.yaml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

Please keep the version specific image

2021-05-13 18:41 UTC, Maxr1998 approved these changes

2021-05-13 19:19 UTC, nielsvanvelzen approved these changes

2021-05-13 19:20 UTC, merged