Fix or suppress detekt warnings and code style issues
jellyfin/jellyfin-android pull request #412
Opened 2021-05-30 20:53 UTC by Maxr1998

2021-05-30 20:58 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
> +                webView.initialize()
Theoretically a behavior change (as the WebView reference isn't captured but accessed through the getter), but should be fine.

2021-05-30 20:58 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/CodecHelpers.kt
> +    }
Fixed this one while I was at it.. see [here](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/mpeg12enc.c#L1176) for context.

2021-05-30 20:58 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
> -                truncated = fragment.getString(R.string.playback_info_and_x_more, size - 3)
This was actually bug, should also be 5. Thanks detekt for forcing me to use a const :smile:

2021-05-30 20:58 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
> +                "- ${stream.displayTitle}$languageString"
Fixes the `null` language showing occasionally.

2021-05-30 20:58 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/utils/JSONExtensions.kt
> -
This was unused, so I removed it. Else I would've fixed the broken iterator..

2021-06-04 15:10 UTC, nielsvanvelzen requested changes

2021-06-04 15:10 UTC, nielsvanvelzen commented on app/build.gradle.kts
> -    ignoreFailures = true
If we add the linter workflow from the SDK this should be kept.. Otherwise the report won't be complete for the GitHub UI.

2021-06-04 15:10 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/player/CodecHelpers.kt
> +     * Level numbers taken from FFmpeg libavcodec/mpeg12enc.c
```suggestion
     * Level numbers taken from FFmpeg libavcodec/mpeg12enc.c.
```

2021-06-04 15:10 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
> +                    bitrate > 1_000 -> "%.2f kbps".format(Locale.getDefault(), bitrate.toDouble() / 1_000)
```suggestion
                    bitrate > 1_000 -> "%.2f Kbps".format(Locale.getDefault(), bitrate.toDouble() / 1_000)
```

2021-06-04 15:10 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
> +                    else -> "%d kbps".format(bitrate / 1000)
```suggestion
                    else -> "%d Kbps".format(bitrate / 1000)
```

2021-06-04 15:10 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
> +            }
You might be able to do:
```suggestion
            override fun onScaleEnd(detector: ScaleGestureDetector) = Unit
```
or
```suggestion
            override fun onScaleEnd(detector: ScaleGestureDetector) = Nothing
```

2021-06-04 20:03 UTC, nielsvanvelzen approved these changes

2021-06-04 20:03 UTC, merged