move back to apksigner signing apks
jellyfin/jellyfin-android pull request #446
Opened 2021-06-19 22:17 UTC by h1dden-da3m0n

### Description

This PR aims to fix our issues with the F-Droid build and our APKs signed via Gradle and not `apksigner` by reverting to using `apksigner`.
Big THANK YOU to @CarlosOlivo figuring this one out!

### Changes

* change apk signing from gradle to apksigner

### Issues

* should fix #414

2021-06-19 22:31 UTC, Maxr1998 approved these changes

2021-06-20 08:05 UTC, nielsvanvelzen requested changes

2021-06-20 08:05 UTC, nielsvanvelzen commented on .github/workflows/app-publish.yaml
> +        id: proprietarySign
```suggestion
        id: proprietarySign
        uses: r0adkll/sign-android-release@v1
```

2021-06-20 12:26 UTC, h1dden-da3m0n commented on .github/workflows/app-publish.yaml
> +        id: proprietarySign
fine lets 'fix'/unify the ordering xD

2021-06-20 12:32 UTC, nielsvanvelzen requested changes

2021-06-20 12:32 UTC, nielsvanvelzen commented on .github/workflows/app-publish.yaml
> +      - name: Sign Libre APK
```suggestion
      - name: Sign libre APK
```

2021-06-20 12:32 UTC, nielsvanvelzen commented on .github/workflows/app-publish.yaml
> +      - name: Sign Proprietary APK
```suggestion
      - name: Sign proprietary APK
```

2021-06-20 13:25 UTC, nielsvanvelzen approved these changes

2021-06-20 14:28 UTC, Maxr1998 approved these changes

2021-06-20 14:29 UTC, merged