add stale issue check workflow
jellyfin/jellyfin-android pull request #609
Opened 2022-01-23 16:32 UTC by h1dden-da3m0n

### Description

This PR aims to add a GitHub Action workflow to monitor, label and close stale issues.
It uses the default GitHub Actions token to comment and close stale Issues (this can be changed if desired).

> NOTE: It explicitly does not touch PRs

### Changes

* add a basic GitHub action workflow to monitor, label, and close stale issues within this repository

### Issues

* successor to the discontinued Stale-Bot config

2022-01-23 18:11 UTC, nielsvanvelzen requested changes

2022-01-23 18:11 UTC, nielsvanvelzen commented on .github/workflows/repo-stale.yaml
> +    runs-on: ubuntu-latest
The workflows in this repository use explicit versions, so this should be `ubuntu-20.04`.

2022-01-23 18:11 UTC, nielsvanvelzen commented on .github/workflows/repo-stale.yaml
> +name: Issue Stale Check
```suggestion
name: Issue stale check
```
For consistency with the "Merge conflict labeler" workflow.

2022-01-23 22:08 UTC, Maxr1998 approved these changes
I fear some good issues could get closed by this since we're not especially fast with fixing them, but you can always bump them, I guess. Should help us direct our focus too.
But generally, this workflow looks good to me.

2022-01-23 22:15 UTC, h1dden-da3m0n commented
> I fear some good issues could get closed by this since we're not especially fast with fixing them, but you can always bump them, I guess. Should help us direct our focus too. But generally, this workflow looks good to me.

as long as you label them `enhancement` or `confirmed` issues will get skipped. You can always also add more to the list of issues to exempt from ever getting stale ;)

2022-01-24 07:55 UTC, nielsvanvelzen approved these changes

2022-01-24 07:55 UTC, merged

2022-01-24 08:17 UTC, Maxr1998 commented
That's good to know. Gotta add a confirmed label then.