Add ability to direct play ass with exoplayer
jellyfin/jellyfin-android pull request #826
Opened 2022-09-30 20:55 UTC by Nalsai

**Changes**
Add a check box in the client settings for ExoPlayer to enable direct play SSA/ASS subtitles without transcoding.

ExoPlayer only partially supports ass subtitles. While support for more features of ass is being worked on it currently only displays it as basic text. Because of that the Jellyfin Android app used to always transcode those subtitles when selected before starting playback. However some people may only have files with basic text in ass subtitles, not care about all the fancy styling or need to avoid transcoding because their server isn't that powerful. Therefore this PR adds the option to direct play ass subtitles.

**Issues**

https://github.com/jellyfin/jellyfin-android/issues/696
https://github.com/jellyfin/jellyfin/issues/7809

2022-09-30 22:54 UTC, Maxr1998 requested changes
Thanks for the PR! That's definitely a good idea.
Have some comments, but otherwise it looks good. Clean and simple solution :+1:

2022-09-30 22:54 UTC, Maxr1998 commented on app/src/main/res/values/strings.xml
> +    <string name="pref_exoplayer_direct_play_ass">Don\'t transcode SSA/ASS subtitles</string>
```suggestion
    <string name="pref_exoplayer_direct_play_ass">Allow SSA/ASS subtitles in direct play</string>
```

2022-09-30 22:54 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
> +    private val appPreferences: AppPreferences by inject()
You should be able to use constructor injection here. On top of my suggestion, you need to add a `get()` parameter in the AppModule.

```suggestion
class DeviceProfileBuilder(
    private val appPreferences: AppPreferences,
) {
```

2022-09-30 22:54 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
> +        else getSubtitleProfiles(EXO_EMBEDDED_SUBTITLES, EXO_EXTERNAL_SUBTITLES);
Can be a `val` (it's immutable) and should probably be a when statement for better readability:
```suggestion
        val subtitleProfiles = when {
            appPreferences.exoPlayerDirectPlayAss -> getSubtitleProfiles(EXO_EMBEDDED_SUBTITLES_ASS, EXO_EXTERNAL_SUBTITLES_ASS)
            else -> getSubtitleProfiles(EXO_EMBEDDED_SUBTITLES, EXO_EXTERNAL_SUBTITLES)
        }
```

*Also I truly like when statements :sweat_smile:*

2022-09-30 22:54 UTC, Maxr1998 commented on app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
> +        private val EXO_EMBEDDED_SUBTITLES_ASS = arrayOf("srt", "subrip", "ttml", "ssa", "ass")
Alternatively, you could do just one constant that only contains the ssa/ass formats (`private val SUBTITLES_SSA = arrayOf("ssa", "ass")`), and append the array to the other one on callsite, like `EXO_EMBEDDED_SUBTITLES + SSA_SUBTITLES`.

2022-09-30 22:54 UTC, Maxr1998 commented on app/src/main/res/values/strings.xml
> +    <string name="pref_exoplayer_direct_play_ass_summary">Play subtitles directly with basic styling to prevent transcoding</string>
```suggestion
    <string name="pref_exoplayer_direct_play_ass_summary">Prevent transcoding and show subtitles with basic styling only. Advanced subtitle styling will not be available if enabled.</string>
```

2022-10-01 12:40 UTC, Maxr1998 approved these changes
Thanks for your contribution!

2022-10-01 12:44 UTC, merged

2025-04-17 13:04 UTC, Asgard70 commented
Bonjour je vois que ç'a été fusionner mais il y a toujours du transcode avec les sous titre ass