Don't ignore detekt failures anymore
jellyfin/jellyfin-android pull request #930
Opened 2022-12-21 01:27 UTC by Maxr1998

2022-12-21 07:22 UTC, nielsvanvelzen requested changes
This option is used for the GH workflow, without it the report is not written.

2022-12-21 12:49 UTC, Maxr1998 commented
Looking at the logs, the report is still written, so it should be fine. I also split the lint and detekt jobs so that they don't influence each other.

2022-12-24 12:14 UTC, nielsvanvelzen commented
I think that's because there's only warnings right now and no errors.

2022-12-24 13:02 UTC, nielsvanvelzen approved these changes

2022-12-24 13:04 UTC, merged